name: Liquidity-Contract Release action

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile
        run: cargo build --release

      - name: Push to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/wasm32-unknown-unknown/release/liquid_stake.opt.wasm"
          token: ${{ secrets.TOKEN }}
          release_name: "V1.0.0"
          release_body: "Guardian protocol release - v1"
          tag: V1.0.0
          draft: false
